# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Mod properties
mod.version=0.1.0
# mod.group=com.ghost
# mod.id == archives_base_name
mod.id=ghostmod
mod.name=Ghost Mod

# Global dependencies
deps.fabric_loader=0.18.1

publish.modrinth=ghostmod
publish.curseforge=1432587
